[profile.default]
memory_limit = 1000000000
lib = "./lib"
optimizer = true
optimizer_runs = 20_000

[profile.user-health]
out = "./out/user-health"
cache_path = "./cache/user-health"
test = "./user-health"

[profile.assets-liability]
out = "./out/assets-liability"
cache_path = "./cache/assets-liability"
test = "./assets-liability"

[rpc_endpoints]
mainnet = "${ETH_RPC}"
